"""First migration

Revision ID: 18165fb13eb1
Revises: 
Create Date: 2024-02-09 21:11:53.820866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18165fb13eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
